name: Unzip File
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip app.zip -d .
      - run: |
          git config --global user.name "YourName"
          git config --global user.email "YourEmail"
          git add .
          git commit -m "Unzipped files"
          git push
